---
- hosts: smartos
  tasks:
  - name: import image
    imgadm:
      uuid: 23ee2dbc-c155-11e6-ab6d-bf5689f582fd
      state: imported
  - name: create lx zone
    vmadm:
      brand: lx
      kernel_version: 3.10.0
      state: present
      alias: c7
      image_uuid: 23ee2dbc-c155-11e6-ab6d-bf5689f582fd
