---
- hosts: smartos
  tasks:
  - name: import image
    imgadm:
      uuid: 23ee2dbc-c155-11e6-ab6d-bf5689f582fd
      state: imported
  - name: create lx zone
    vmadm:
      brand: lx
      kernel_version: 3.10.0
      state: present
      alias: c7
      hostname: c7
      image_uuid: 23ee2dbc-c155-11e6-ab6d-bf5689f582fd
      resolvers: 10.76.78.2
      customer_metadata:
        root_authorized_keys: "{{ lookup('file', 'public.key') }}"
        user-script: "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys ; /usr/sbin/mdata-get root_authorized_keys > ~admin/.ssh/authorized_keys"
      nics:
      - nic_tag: admin
        ip: "{{ hostvars['zone1']['ansible_host'] }}"
        netmask: 255.255.255.0
        gateway: 10.76.78.10
        primary: true
        allow_ip_spoofing: true
      - nic_tag: switch0
        ip: 10.76.79.1
        netmask: 255.255.255.0
        allow_ip_spoofing: true
  - name: create lx zone 2
    vmadm:
      brand: lx
      kernel_version: 3.10.0
      state: present
      alias: c72
      hostname: c72
      image_uuid: 23ee2dbc-c155-11e6-ab6d-bf5689f582fd
      customer_metadata:
        root_authorized_keys: "{{ lookup('file', 'public.key') }}"
        user-script: "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys ; /usr/sbin/mdata-get root_authorized_keys > ~admin/.ssh/authorized_keys"
      nics:
      - nic_tag: switch0
        ip: 10.76.79.2
        netmask: 255.255.255.0
        allow_ip_spoofing: true
